version: "3.9"

services:
  easyconnect-sslvpn-socks5:
    image: hagb/docker-easyconnect:cli
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - vpn-cli-opts.env
    environment: 
      EC_VER: 7.6.7
    networks: 
      - sslvpn
    healthcheck:
      test: pidof svpnservice > /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  # easyconnect-mock:
  #   build:
  #     context: ../../web-automation/test/
  #     dockerfile: socks5-test.dockerfile
  #   networks: 
  #     - sslvpn
  #   healthcheck:
  #     test: pidof socks5-test > /dev/null || exit 1
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  node-job-cc:
    image: node:alpine3.13
    depends_on: 
      - easyconnect-sslvpn-socks5
    volumes:
      - ../../web-automation:/app
    working_dir: /app
    command: >-
      sh -c ' 
      sleep 5 && npm install >/dev/null &&
      node coronavirus-chore.js --socks5 "socks5://easyconnect-sslvpn-socks5:1080"
      '
    # restart: on-failure
    networks: 
      - sslvpn

networks: 
  sslvpn: