name: Mocking

on:
  workflow_dispatch:

jobs:
  run-cc:
    environment: mock
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v2
      # node
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Tragically failing
        run: exit 1
      - name: Report Status
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            const notify = require("./.github/scripts/notify.js");
            const env = name => process.env[name];
            await notify(
              env("WEBHOOK_URL"), env("WEBHOOK_KEY"), env("WEBHOOK_SECRET")
            );
        env:
          WEBHOOK_URL: ${{ secrets.NOTIFY_WEBHOOK_URL }}
          WEBHOOK_KEY: ${{ secrets.NOTIFY_WEBHOOK_KEY }}
          WEBHOOK_SECRET: ${{ secrets.NOTIFY_WEBHOOK_SECRET }}
          INPUT_STATUS: "failed"
          INPUT_TOKEN: ${{ secrets.NOTIFY_GITHUB_TOKEN }}
          INPUT_NOTIFICATION_TITLE: ${{ secrets.NOTIFY_TITLE }}